apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - overpass.yaml
patches:
  - target:
      kind: ConfigMap
      name: gods-eye-view-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gods-eye-view-config
      data:
        OVERPASS_REGIONAL_URL: http://overpass-austin/api/interpreter
        OVERPASS_REGIONAL_BOUNDS: "29.9,-98.2,30.7,-97.2"
