apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: gods-eye-view-auth-settings
    files:
      - oauth2-proxy.cfg
