apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: gods-eye-view-acme-server
    files:
      - server.mjs
  - name: gods-eye-view-acme-token
    literals:
      - token=
      - authorization=
    options:
      disableNameSuffixHash: true
