apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gods-eye-view-deny-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gods-eye-view
  policyTypes:
    - Ingress
