apiVersion: v1
kind: Service
metadata:
  name: gods-eye-view
  labels:
    app.kubernetes.io/name: gods-eye-view
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gods-eye-view
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
